title: Santiago Flores - Mechanical Engineer
description: Personal Website.
theme: minima
author: Santiago Flores
email: san.flo.lo@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanflolo.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

footer_text: "© 2025 Santiago Flores. All rights reserved."
footer_links:
  - title: "CV"
    url: "cv.md"
  - title: "Design Portfolio"
    url: "#portfolio"
  - title: "Contact"
    url: "contact.md"